# 02 — Judge Scoring

Run all 50 evaluation instances through each of the three Ollama judge models and record
the raw scores.

**Prerequisites:**
- Notebook 01 has been run (answer corpus and human scores exist in `data/`)
- `ollama` is installed (`make setup` handles this)
- Models are pulled: `make setup` pulls `qwen2.5:3b`, `gemma3:4b`, `llama3.2:3b`

> **Do NOT run `ollama serve` manually.** This notebook starts and restarts Ollama
> automatically. A parallel terminal instance causes "address already in use" errors.

**Outputs produced:**
- `data/eval/scores_qwen2_5_1_5b.json`
- `data/eval/scores_gemma3_1b.json`
- `data/eval/scores_llama3_2_1b.json`

> **RAM constraint:** Models are scored sequentially. All three models are under 1.5 GB —
> do not run two judges simultaneously in the same Codespace.

In [1]:
import math
import os
import socket
import subprocess
import sys
from pathlib import Path

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import httpx
import json
import time

import pandas as pd

from src.config import load_settings
from src.judging.judge import OllamaJudge
from src.judging.runner import METRICS

settings = load_settings(ROOT / "config" / "settings.yaml")
print(f"Ollama URL: {settings.ollama_url}")
print(f"Models: {settings.models}")

FIGURES_DIR = ROOT / "outputs" / "figures"
RESULTS_DIR = ROOT / "outputs" / "results"
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)


# ── helpers ───────────────────────────────────────────────────────────────────

def _nan_count(records: list) -> int:
    return sum(1 for r in records if isinstance(r.get("score"), float) and math.isnan(r["score"]))


def _port_free(port: int = 11434) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) != 0


def drop_page_cache() -> None:
    """Release Linux page/slab/dentry caches (the buff/cache shown in free -m)."""
    result = subprocess.run(
        ["sudo", "sh", "-c", "sync; echo 3 > /proc/sys/vm/drop_caches"],
        capture_output=True,
    )
    if result.returncode == 0:
        print("  Page cache dropped.")
    else:
        print(f"  drop_caches skipped (no sudo or not supported): {result.stderr.decode().strip()}")


def ensure_ollama_running(ollama_url: str, timeout: int = 60) -> bool:
    """Start Ollama if it is not already running. Returns True when ready."""
    if not _port_free():
        return True  # already running
    print("Ollama not running — starting ollama serve...", end=" ", flush=True)
    env = {**os.environ, "OLLAMA_NUM_PARALLEL": "1", "OLLAMA_MAX_LOADED_MODELS": "1"}
    subprocess.Popen(
        ["ollama", "serve"],
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            httpx.get(f"{ollama_url}/api/tags", timeout=3.0)
            print("ready.")
            return True
        except Exception:
            time.sleep(2)
    print("WARNING: Ollama did not start within timeout.")
    return False


def restart_ollama(ollama_url: str, timeout: int = 60) -> None:
    """Kill Ollama + its llama runner child, drop page cache, start fresh."""
    print("  Restarting Ollama...", end=" ", flush=True)
    subprocess.run(["pkill", "-TERM", "-f", "ollama serve"], capture_output=True)
    for _ in range(20):  # wait up to 10 s for port to be released
        if _port_free():
            break
        time.sleep(0.5)
    else:
        subprocess.run(["pkill", "-KILL", "-f", "ollama serve"], capture_output=True)
        time.sleep(1)
    # Kill orphaned llama runner — it holds model weights in RAM for several
    # seconds after the Ollama server exits, causing OOM when the next model loads.
    subprocess.run(["pkill", "-KILL", "-f", "ollama_llama_server"], capture_output=True)
    time.sleep(4)  # let runner fully exit and release RAM before dropping cache
    drop_page_cache()
    env = {**os.environ, "OLLAMA_NUM_PARALLEL": "1", "OLLAMA_MAX_LOADED_MODELS": "1"}
    subprocess.Popen(
        ["ollama", "serve"],
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            httpx.get(f"{ollama_url}/api/tags", timeout=3.0)
            print("ready.")
            return
        except Exception:
            time.sleep(2)
    print("WARNING: Ollama did not restart within timeout.")

Ollama URL: http://localhost:11434
Models: ['gemma3:4b', 'llama3.1:8b', 'qwen2.5:7b']

## 1. Load answer corpus

In [2]:
answers_dir = ROOT / "data" / "answers"

all_instances = []
for path in sorted(answers_dir.glob("*.json")):
    data = json.loads(path.read_text())
    if isinstance(data, list):
        all_instances.extend(data)
    else:
        all_instances.append(data)

print(f"Loaded {len(all_instances)} instances from {answers_dir}")
pd.DataFrame(all_instances).groupby(["pipeline", "question_type"]).size().rename("count").reset_index()

Loaded 50 instances from /workspaces/llm_judge_benchmark/data/answers

      pipeline      question_type  count
0        graph  absence_reasoning      5
1        graph          multi_hop      6
2        graph         single_hop      9
3  handcrafted  absence_reasoning      3
4  handcrafted          multi_hop      3
5  handcrafted         single_hop      4
6       vector  absence_reasoning      5
7       vector          multi_hop      6
8       vector         single_hop      9

## 2. Check Ollama availability

In [3]:
ensure_ollama_running(settings.ollama_url)

try:
    resp = httpx.get(f"{settings.ollama_url}/api/tags", timeout=5.0)
    available_models = [m["name"] for m in resp.json().get("models", [])]
    print(f"Ollama is running. Available models: {available_models}")
except Exception as e:
    print(f"Ollama not reachable: {e}")
    print("Check that 'ollama' is installed: curl -fsSL https://ollama.com/install.sh | sh")
    available_models = []

Ollama is running. Available models: ['llama3.1:8b', 'qwen2.5:7b', 'gemma3:4b']

## 3. Score all instances

Each model is scored independently. Results are written to `data/eval/` after each model
so progress survives interruptions. Ollama is restarted before each model for a clean
memory slate — no manual terminal commands needed.

Estimated times on a 2-CPU Codespace (includes Ollama restart overhead):
- `qwen2.5:3b`: ~15 min
- `gemma3:4b`: ~12 min
- `llama3.2:3b`: ~10 min

In [4]:
# ── Configuration ──────────────────────────────────────────────────────────────
# FORCE_RESCORE = True  → always re-score, even if a valid file exists.
# FORCE_RESCORE = False → skip models with complete, NaN-free score files only.
#                         Models with missing files OR any NaN scores are re-scored automatically.
FORCE_RESCORE = True # False

eval_dir = ROOT / "data" / "eval"
eval_dir.mkdir(parents=True, exist_ok=True)

print("Score file status:\n")
for model in settings.models:
    safe = model.replace(":", "_").replace(".", "_")
    out_path = eval_dir / f"scores_{safe}.json"
    if out_path.exists():
        records = json.loads(out_path.read_text())
        nans = _nan_count(records)
        if not records:
            tag, detail, action = "[EMPTY]", "0 records", "will score"
        elif nans > 0:
            tag = "[NaN]"
            detail = f"{len(records)} records, {nans} NaN"
            action = "will RE-SCORE (NaN found)" if not FORCE_RESCORE else "will RE-SCORE (forced)"
        else:
            tag = "[OK]"
            detail = f"{len(records)} records, 0 NaN"
            action = "SKIP" if not FORCE_RESCORE else "will RE-SCORE (forced)"
    else:
        tag, detail, action = "[MISSING]", "—", "will score"
    print(f"  {tag:<10} {out_path.name:<32} {detail:<26} → {action}")

Score file status:

  [MISSING]  scores_gemma3_4b.json            —                          → will score
  [MISSING]  scores_llama3_1_8b.json          —                          → will score
  [MISSING]  scores_qwen2_5_7b.json           —                          → will score

In [5]:
def score_model(model: str, instances: list, output_dir: Path) -> list:
    """Score all instances with one judge using a single combined call per instance."""
    judge = OllamaJudge(model=model, ollama_url=settings.ollama_url, num_ctx=settings.num_ctx)
    records = []
    total = len(instances)
    t0 = time.perf_counter()

    for inst_idx, instance in enumerate(instances, 1):
        try:
            scores = judge.score_all_metrics(
                question=str(instance["question"]),
                context=instance["context"],
                answer=str(instance["answer"]),
            )
        except Exception as exc:
            print(f"  ERROR {instance['id']}: {exc}")
            scores = {m: float("nan") for m in METRICS}

        for metric, score in scores.items():
            records.append({"id": instance["id"], "model": model, "metric": metric, "score": score})

        elapsed = time.perf_counter() - t0
        rate = inst_idx / elapsed if elapsed > 0 else 0
        eta = (total - inst_idx) / rate if rate > 0 else 0
        score_summary = ", ".join(f"{m[:4]}={scores[m]:.3f}" for m in METRICS)
        print(f"  [{model}] {inst_idx}/{total}: {score_summary}  ({elapsed:.0f}s elapsed, ETA {eta:.0f}s)")

    elapsed = time.perf_counter() - t0
    safe = model.replace(":", "_").replace(".", "_")
    out_path = output_dir / f"scores_{safe}.json"
    out_path.write_text(json.dumps(records, indent=2))
    print(f"  Saved {len(records)} records to {out_path}  ({elapsed:.1f}s total)")
    return records

In [6]:
timing = {}

for model in settings.models:
    safe = model.replace(":", "_").replace(".", "_")
    out_path = eval_dir / f"scores_{safe}.json"

    if not FORCE_RESCORE and out_path.exists():
        existing = json.loads(out_path.read_text())
        nans = _nan_count(existing)
        if existing and nans == 0:
            print(f"SKIP {model}: {len(existing)} valid records in {out_path.name}")
            continue
        reason = f"{nans} NaN scores" if nans > 0 else "empty file"
        print(f"RE-SCORE {model}: {reason} in {out_path.name}, deleting and re-running")
        out_path.unlink()

    if model not in available_models:
        print(f"SKIP {model}: not available in Ollama (pull with: ollama pull {model})")
        continue

    # Restart Ollama for a clean memory slate — avoids state corruption from
    # the previous model and eliminates residual KV-cache allocations.
    restart_ollama(settings.ollama_url)

    # Warm up: load the model and confirm it responds before the scoring loop.
    judge_check = OllamaJudge(model=model, ollama_url=settings.ollama_url, num_ctx=settings.num_ctx)
    if not judge_check.warm_up(timeout=120.0):
        print(f"  SKIP {model}: model failed to load after Ollama restart")
        continue

    print(f"\nScoring with {model} ({len(all_instances)} instances \u00d7 {len(METRICS)} metrics)...")
    t0 = time.perf_counter()
    score_model(model, all_instances, eval_dir)
    timing[model] = time.perf_counter() - t0

if timing:
    print("\n=== Timing summary ===")
    for m, t in timing.items():
        print(f"  {m}: {t/60:.1f} min")
else:
    print("\nAll models skipped (already scored or unavailable).")

  Restarting Ollama...   Page cache dropped.

2026-05-15 13:19:01.011 | INFO     | src.judging.judge:warm_up:85 - gemma3:4b | warming up (model load may take up to 120s)...

ready.

2026-05-15 13:19:11.449 | INFO     | src.judging.judge:warm_up:99 - gemma3:4b | warm-up complete, model is ready

Scoring with gemma3:4b (50 instances × 3 metrics)...

2026-05-15 13:19:38.189 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 1/50: cont=1.000, grou=1.000, answ=1.000  (27s elapsed, ETA 1310s)

2026-05-15 13:19:51.616 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 2/50: cont=1.000, grou=1.000, answ=1.000  (40s elapsed, ETA 964s)

2026-05-15 13:20:01.830 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.5,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.5, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 3/50: cont=0.500, grou=1.000, answ=1.000  (50s elapsed, ETA 789s)

2026-05-15 13:20:13.147 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 4/50: cont=1.000, grou=1.000, answ=1.000  (62s elapsed, ETA 710s)

2026-05-15 13:20:25.753 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 5/50: cont=1.000, grou=1.000, answ=1.000  (74s elapsed, ETA 669s)

2026-05-15 13:20:40.662 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 6/50: cont=1.000, grou=1.000, answ=1.000  (89s elapsed, ETA 654s)

2026-05-15 13:20:51.234 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.8,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 7/50: cont=0.800, grou=1.000, answ=1.000  (100s elapsed, ETA 613s)

2026-05-15 13:21:02.836 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 8/50: cont=1.000, grou=1.000, answ=1.000  (111s elapsed, ETA 585s)

2026-05-15 13:21:14.049 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 9/50: cont=1.000, grou=1.000, answ=1.000  (123s elapsed, ETA 559s)

2026-05-15 13:21:26.676 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 10/50: cont=1.000, grou=1.000, answ=1.000  (135s elapsed, ETA 541s)

2026-05-15 13:21:39.130 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 11/50: cont=1.000, grou=1.000, answ=1.000  (148s elapsed, ETA 524s)

2026-05-15 13:21:50.294 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 12/50: cont=1.000, grou=1.000, answ=1.000  (159s elapsed, ETA 503s)

2026-05-15 13:22:02.197 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.9,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.9, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 13/50: cont=0.900, grou=1.000, answ=1.000  (171s elapsed, ETA 486s)

2026-05-15 13:22:11.521 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.7,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.7, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 14/50: cont=0.700, grou=1.000, answ=1.000  (180s elapsed, ETA 463s)

2026-05-15 13:22:23.900 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 15/50: cont=1.000, grou=1.000, answ=1.000  (192s elapsed, ETA 449s)

2026-05-15 13:22:35.781 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 16/50: cont=1.000, grou=1.000, answ=1.000  (204s elapsed, ETA 434s)

2026-05-15 13:22:45.598 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.5,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.5, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 17/50: cont=0.500, grou=1.000, answ=1.000  (214s elapsed, ETA 416s)

2026-05-15 13:22:57.334 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 18/50: cont=1.000, grou=1.000, answ=1.000  (226s elapsed, ETA 402s)

2026-05-15 13:23:09.899 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 19/50: cont=1.000, grou=1.000, answ=1.000  (238s elapsed, ETA 389s)

2026-05-15 13:23:20.571 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.7,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.7, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 20/50: cont=0.700, grou=1.000, answ=1.000  (249s elapsed, ETA 374s)

2026-05-15 13:23:31.348 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 21/50: cont=1.000, grou=1.000, answ=1.000  (260s elapsed, ETA 359s)

2026-05-15 13:23:38.859 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 0.9,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [gemma3:4b] 22/50: cont=1.000, grou=0.900, answ=1.000  (267s elapsed, ETA 340s)

2026-05-15 13:23:46.647 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 0.6,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 0.6, 'answer_relevance': 1.0}

  [gemma3:4b] 23/50: cont=1.000, grou=0.600, answ=1.000  (275s elapsed, ETA 323s)

2026-05-15 13:23:58.022 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 24/50: cont=1.000, grou=1.000, answ=1.000  (287s elapsed, ETA 310s)

2026-05-15 13:24:04.948 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.6,\n  "groundedness": 0.2,\n  "answer_relevance": 0.4\n}\n```' | scores={'context_relevance': 0.6, 'groundedness': 0.2, 'answer_relevance': 0.4}

  [gemma3:4b] 25/50: cont=0.600, grou=0.200, answ=0.400  (293s elapsed, ETA 293s)

2026-05-15 13:24:12.143 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.5,\n  "groundedness": 0.0,\n  "answer_relevance": 0.0\n}\n```' | scores={'context_relevance': 0.5, 'groundedness': 0.0, 'answer_relevance': 0.0}

  [gemma3:4b] 26/50: cont=0.500, grou=0.000, answ=0.000  (301s elapsed, ETA 278s)

2026-05-15 13:24:23.189 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.7,\n  "groundedness": 0.9,\n  "answer_relevance": 0.9\n}\n```' | scores={'context_relevance': 0.7, 'groundedness': 0.9, 'answer_relevance': 0.9}

  [gemma3:4b] 27/50: cont=0.700, grou=0.900, answ=0.900  (312s elapsed, ETA 266s)

2026-05-15 13:24:30.343 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.6,\n  "groundedness": 0.0,\n  "answer_relevance": 0.3\n}\n```' | scores={'context_relevance': 0.6, 'groundedness': 0.0, 'answer_relevance': 0.3}

  [gemma3:4b] 28/50: cont=0.600, grou=0.000, answ=0.300  (319s elapsed, ETA 251s)

2026-05-15 13:24:37.881 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.7,\n  "groundedness": 0.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.7, 'groundedness': 0.0, 'answer_relevance': 1.0}

  [gemma3:4b] 29/50: cont=0.700, grou=0.000, answ=1.000  (326s elapsed, ETA 236s)

2026-05-15 13:24:49.241 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 30/50: cont=1.000, grou=1.000, answ=1.000  (338s elapsed, ETA 225s)

2026-05-15 13:25:01.118 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 31/50: cont=1.000, grou=1.000, answ=1.000  (350s elapsed, ETA 214s)

2026-05-15 13:25:14.587 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 32/50: cont=1.000, grou=1.000, answ=1.000  (363s elapsed, ETA 204s)

2026-05-15 13:25:24.672 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.5,\n  "groundedness": 0.0,\n  "answer_relevance": 0.0\n}\n```' | scores={'context_relevance': 0.5, 'groundedness': 0.0, 'answer_relevance': 0.0}

  [gemma3:4b] 33/50: cont=0.500, grou=0.000, answ=0.000  (373s elapsed, ETA 192s)

2026-05-15 13:25:35.864 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 34/50: cont=1.000, grou=1.000, answ=1.000  (384s elapsed, ETA 181s)

2026-05-15 13:25:48.671 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 35/50: cont=1.000, grou=1.000, answ=1.000  (397s elapsed, ETA 170s)

2026-05-15 13:26:03.504 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 36/50: cont=1.000, grou=1.000, answ=1.000  (412s elapsed, ETA 160s)

2026-05-15 13:26:13.963 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.7,\n  "groundedness": 0.6,\n  "answer_relevance": 0.8\n}\n```' | scores={'context_relevance': 0.7, 'groundedness': 0.6, 'answer_relevance': 0.8}

  [gemma3:4b] 37/50: cont=0.700, grou=0.600, answ=0.800  (423s elapsed, ETA 148s)

2026-05-15 13:26:25.741 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 38/50: cont=1.000, grou=1.000, answ=1.000  (434s elapsed, ETA 137s)

2026-05-15 13:26:36.871 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 39/50: cont=1.000, grou=1.000, answ=1.000  (445s elapsed, ETA 126s)

2026-05-15 13:26:49.542 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 40/50: cont=1.000, grou=1.000, answ=1.000  (458s elapsed, ETA 115s)

2026-05-15 13:27:02.039 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 41/50: cont=1.000, grou=1.000, answ=1.000  (471s elapsed, ETA 103s)

2026-05-15 13:27:13.208 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 42/50: cont=1.000, grou=1.000, answ=1.000  (482s elapsed, ETA 92s)

2026-05-15 13:27:25.094 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.9,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.9, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 43/50: cont=0.900, grou=1.000, answ=1.000  (494s elapsed, ETA 80s)

2026-05-15 13:27:34.505 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.5,\n  "groundedness": 0.0,\n  "answer_relevance": 0.0\n}\n```' | scores={'context_relevance': 0.5, 'groundedness': 0.0, 'answer_relevance': 0.0}

  [gemma3:4b] 44/50: cont=0.500, grou=0.000, answ=0.000  (503s elapsed, ETA 69s)

2026-05-15 13:27:47.151 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 45/50: cont=1.000, grou=1.000, answ=1.000  (516s elapsed, ETA 57s)

2026-05-15 13:27:59.044 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 46/50: cont=1.000, grou=1.000, answ=1.000  (528s elapsed, ETA 46s)

2026-05-15 13:28:08.809 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.6,\n  "groundedness": 0.0,\n  "answer_relevance": 0.2\n}\n```' | scores={'context_relevance': 0.6, 'groundedness': 0.0, 'answer_relevance': 0.2}

  [gemma3:4b] 47/50: cont=0.600, grou=0.000, answ=0.200  (537s elapsed, ETA 34s)

2026-05-15 13:28:20.591 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 48/50: cont=1.000, grou=1.000, answ=1.000  (549s elapsed, ETA 23s)

2026-05-15 13:28:33.354 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [gemma3:4b] 49/50: cont=1.000, grou=1.000, answ=1.000  (562s elapsed, ETA 11s)

2026-05-15 13:28:44.479 | DEBUG    | src.judging.judge:score_all_metrics:64 - gemma3:4b | combined | raw='```json\n{\n  "context_relevance": 0.5,\n  "groundedness": 0.0,\n  "answer_relevance": 0.0\n}\n```' | scores={'context_relevance': 0.5, 'groundedness': 0.0, 'answer_relevance': 0.0}

  [gemma3:4b] 50/50: cont=0.500, grou=0.000, answ=0.000  (573s elapsed, ETA 0s)
  Saved 150 records to /workspaces/llm_judge_benchmark/data/eval/scores_gemma3_4b.json  (573.0s total)
  Restarting Ollama...   Page cache dropped.

2026-05-15 13:28:54.313 | INFO     | src.judging.judge:warm_up:85 - llama3.1:8b | warming up (model load may take up to 120s)...

ready.

2026-05-15 13:29:09.271 | INFO     | src.judging.judge:warm_up:99 - llama3.1:8b | warm-up complete, model is ready

Scoring with llama3.1:8b (50 instances × 3 metrics)...

2026-05-15 13:29:52.769 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n    "context_relevance": 0.8,\n    "groundedness": 0.9,\n    "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [llama3.1:8b] 1/50: cont=0.800, grou=0.900, answ=1.000  (43s elapsed, ETA 2131s)

2026-05-15 13:30:13.568 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n  "context_relevance": 0.9,\n  "groundedness": 0.8,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.9, 'groundedness': 0.8, 'answer_relevance': 1.0}

  [llama3.1:8b] 2/50: cont=0.900, grou=0.800, answ=1.000  (64s elapsed, ETA 1543s)

2026-05-15 13:30:28.873 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 0.8,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 3/50: cont=0.800, grou=1.000, answ=1.000  (80s elapsed, ETA 1247s)

2026-05-15 13:30:46.925 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n    "context_relevance": 0.8,\n    "groundedness": 1.0,\n    "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 4/50: cont=0.800, grou=1.000, answ=1.000  (98s elapsed, ETA 1123s)

2026-05-15 13:31:05.644 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n  "context_relevance": 0.9,\n  "groundedness": 1.0,\n  "answer_relevance": 0.8\n}\n```' | scores={'context_relevance': 0.9, 'groundedness': 1.0, 'answer_relevance': 0.8}

  [llama3.1:8b] 5/50: cont=0.900, grou=1.000, answ=0.800  (116s elapsed, ETA 1047s)

2026-05-15 13:31:27.669 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 1.0,\n  "groundedness": 0.8,\n  "answer_relevance": 1.0\n}' | scores={'context_relevance': 1.0, 'groundedness': 0.8, 'answer_relevance': 1.0}

  [llama3.1:8b] 6/50: cont=1.000, grou=0.800, answ=1.000  (138s elapsed, ETA 1015s)

2026-05-15 13:31:44.041 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n  "context_relevance": 0.9,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.9, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 7/50: cont=0.900, grou=1.000, answ=1.000  (155s elapsed, ETA 951s)

2026-05-15 13:32:01.529 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n    "context_relevance": 1.0,\n    "groundedness": 1.0,\n    "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 8/50: cont=1.000, grou=1.000, answ=1.000  (172s elapsed, ETA 904s)

2026-05-15 13:32:18.507 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 0.8,\n  "answer_relevance": 0.5\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 0.8, 'answer_relevance': 0.5}

  [llama3.1:8b] 9/50: cont=1.000, grou=0.800, answ=0.500  (189s elapsed, ETA 862s)

2026-05-15 13:32:38.663 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 0.9,\n  "groundedness": 0.7,\n  "answer_relevance": 0.9\n}\n```' | scores={'context_relevance': 0.9, 'groundedness': 0.7, 'answer_relevance': 0.9}

  [llama3.1:8b] 10/50: cont=0.900, grou=0.700, answ=0.900  (209s elapsed, ETA 838s)

2026-05-15 13:32:57.703 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n    "context_relevance": 1.0,\n    "groundedness": 1.0,\n    "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 11/50: cont=1.000, grou=1.000, answ=1.000  (228s elapsed, ETA 810s)

2026-05-15 13:33:14.909 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 0.8,\n  "groundedness": 0.9,\n  "answer_relevance": 0.5\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 0.5}

  [llama3.1:8b] 12/50: cont=0.800, grou=0.900, answ=0.500  (246s elapsed, ETA 778s)

2026-05-15 13:33:32.621 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n    "context_relevance": 1.0,\n    "groundedness": 0.9,\n    "answer_relevance": 1.0\n}' | scores={'context_relevance': 1.0, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [llama3.1:8b] 13/50: cont=1.000, grou=0.900, answ=1.000  (263s elapsed, ETA 750s)

2026-05-15 13:33:46.080 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 0.0\n}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 0.0}

  [llama3.1:8b] 14/50: cont=1.000, grou=1.000, answ=0.000  (277s elapsed, ETA 712s)

2026-05-15 13:34:04.579 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 15/50: cont=1.000, grou=1.000, answ=1.000  (295s elapsed, ETA 689s)

2026-05-15 13:34:22.310 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 0.5,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}' | scores={'context_relevance': 0.5, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 16/50: cont=0.500, grou=1.000, answ=1.000  (313s elapsed, ETA 665s)

2026-05-15 13:34:36.427 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n"context_relevance": 0.8,\n"groundedness": 0.0,\n"answer_relevance": 1.0\n}' | scores={'context_relevance': 0.8, 'groundedness': 0.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 17/50: cont=0.800, grou=0.000, answ=1.000  (327s elapsed, ETA 635s)

2026-05-15 13:34:53.505 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 18/50: cont=1.000, grou=1.000, answ=1.000  (344s elapsed, ETA 612s)

2026-05-15 13:35:13.818 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n  "context_relevance": 0.8,\n  "groundedness": 0.9,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [llama3.1:8b] 19/50: cont=0.800, grou=0.900, answ=1.000  (365s elapsed, ETA 595s)

2026-05-15 13:35:30.482 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n    "context_relevance": 0.5,\n    "groundedness": 1.0,\n    "answer_relevance": 0.0\n}\n```' | scores={'context_relevance': 0.5, 'groundedness': 1.0, 'answer_relevance': 0.0}

  [llama3.1:8b] 20/50: cont=0.500, grou=1.000, answ=0.000  (381s elapsed, ETA 572s)

2026-05-15 13:35:46.779 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 0.8,\n  "answer_relevance": 0.6\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 0.8, 'answer_relevance': 0.6}

  [llama3.1:8b] 21/50: cont=1.000, grou=0.800, answ=0.600  (398s elapsed, ETA 549s)

2026-05-15 13:35:57.016 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 0.8,\n  "groundedness": 0.9,\n  "answer_relevance": 0.6\n}' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 0.6}

  [llama3.1:8b] 22/50: cont=0.800, grou=0.900, answ=0.600  (408s elapsed, ETA 519s)

2026-05-15 13:36:07.468 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 0.9,\n  "groundedness": 0.8,\n  "answer_relevance": 0.6\n}' | scores={'context_relevance': 0.9, 'groundedness': 0.8, 'answer_relevance': 0.6}

  [llama3.1:8b] 23/50: cont=0.900, grou=0.800, answ=0.600  (418s elapsed, ETA 491s)

2026-05-15 13:36:25.333 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n  "context_relevance": 1.0,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 24/50: cont=1.000, grou=1.000, answ=1.000  (436s elapsed, ETA 472s)

2026-05-15 13:36:35.133 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 0.8,\n  "groundedness": 0.2,\n  "answer_relevance": 0.4\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 0.2, 'answer_relevance': 0.4}

  [llama3.1:8b] 25/50: cont=0.800, grou=0.200, answ=0.400  (446s elapsed, ETA 446s)

2026-05-15 13:36:44.226 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n"answer_relevance": 0.0,\n"context_relevance": 1.0,\n"groundedness": 0.0\n}' | scores={'context_relevance': 1.0, 'groundedness': 0.0, 'answer_relevance': 0.0}

  [llama3.1:8b] 26/50: cont=1.000, grou=0.000, answ=0.000  (455s elapsed, ETA 420s)

2026-05-15 13:37:01.065 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n    "context_relevance": 0.8,\n    "groundedness": 1.0,\n    "answer_relevance": 0.6\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 1.0, 'answer_relevance': 0.6}

  [llama3.1:8b] 27/50: cont=0.800, grou=1.000, answ=0.600  (472s elapsed, ETA 402s)

2026-05-15 13:37:10.634 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 0.7,\n  "groundedness": 0.5,\n  "answer_relevance": 0.3\n}' | scores={'context_relevance': 0.7, 'groundedness': 0.5, 'answer_relevance': 0.3}

  [llama3.1:8b] 28/50: cont=0.700, grou=0.500, answ=0.300  (481s elapsed, ETA 378s)

2026-05-15 13:37:20.843 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n    "context_relevance": 0.8,\n    "groundedness": 0.9,\n    "answer_relevance": 1.0\n}' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [llama3.1:8b] 29/50: cont=0.800, grou=0.900, answ=1.000  (492s elapsed, ETA 356s)

2026-05-15 13:37:37.373 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n    "context_relevance": 1.0,\n    "groundedness": 1.0,\n    "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 30/50: cont=1.000, grou=1.000, answ=1.000  (508s elapsed, ETA 339s)

2026-05-15 13:37:55.474 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n    "context_relevance": 0.8,\n    "groundedness": 0.9,\n    "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [llama3.1:8b] 31/50: cont=0.800, grou=0.900, answ=1.000  (526s elapsed, ETA 323s)

2026-05-15 13:38:15.360 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 0.5,\n  "groundedness": 0.9,\n  "answer_relevance": 1.0\n}' | scores={'context_relevance': 0.5, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [llama3.1:8b] 32/50: cont=0.500, grou=0.900, answ=1.000  (546s elapsed, ETA 307s)

2026-05-15 13:38:29.817 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 0.8,\n  "groundedness": 0.6,\n  "answer_relevance": 1.0\n}' | scores={'context_relevance': 0.8, 'groundedness': 0.6, 'answer_relevance': 1.0}

  [llama3.1:8b] 33/50: cont=0.800, grou=0.600, answ=1.000  (561s elapsed, ETA 289s)

2026-05-15 13:38:46.362 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n"context_relevance": 0.9,\n"groundedness": 1.0,\n"answer_relevance": 1.0\n}' | scores={'context_relevance': 0.9, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 34/50: cont=0.900, grou=1.000, answ=1.000  (577s elapsed, ETA 272s)

2026-05-15 13:39:04.975 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 0.8,\n  "groundedness": 0.9,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [llama3.1:8b] 35/50: cont=0.800, grou=0.900, answ=1.000  (596s elapsed, ETA 255s)

2026-05-15 13:39:27.673 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n    "context_relevance": 1.0,\n    "groundedness": 1.0,\n    "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 36/50: cont=1.000, grou=1.000, answ=1.000  (618s elapsed, ETA 240s)

2026-05-15 13:39:43.234 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 0.8,\n  "groundedness": 0.6,\n  "answer_relevance": 0.4\n}' | scores={'context_relevance': 0.8, 'groundedness': 0.6, 'answer_relevance': 0.4}

  [llama3.1:8b] 37/50: cont=0.800, grou=0.600, answ=0.400  (634s elapsed, ETA 223s)

2026-05-15 13:40:00.625 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 1.0,\n  "groundedness": 0.5,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 0.5, 'answer_relevance': 1.0}

  [llama3.1:8b] 38/50: cont=1.000, grou=0.500, answ=1.000  (651s elapsed, ETA 206s)

2026-05-15 13:40:17.369 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 1.0,\n  "groundedness": 0.0,\n  "answer_relevance": 0.0\n}\n```' | scores={'context_relevance': 1.0, 'groundedness': 0.0, 'answer_relevance': 0.0}

  [llama3.1:8b] 39/50: cont=1.000, grou=0.000, answ=0.000  (668s elapsed, ETA 188s)

2026-05-15 13:40:35.965 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n"answer_relevance": 1.0,\n"context_relevance": 1.0,\n"groundedness": 1.0\n}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 40/50: cont=1.000, grou=1.000, answ=1.000  (687s elapsed, ETA 172s)

2026-05-15 13:40:54.376 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 1.0,\n  "groundedness": 0.8,\n  "answer_relevance": 1.0\n}' | scores={'context_relevance': 1.0, 'groundedness': 0.8, 'answer_relevance': 1.0}

  [llama3.1:8b] 41/50: cont=1.000, grou=0.800, answ=1.000  (705s elapsed, ETA 155s)

2026-05-15 13:41:11.599 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 0.9,\n  "groundedness": 0.8,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.9, 'groundedness': 0.8, 'answer_relevance': 1.0}

  [llama3.1:8b] 42/50: cont=0.900, grou=0.800, answ=1.000  (722s elapsed, ETA 138s)

2026-05-15 13:41:29.957 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 0.7,\n  "groundedness": 0.9,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.7, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [llama3.1:8b] 43/50: cont=0.700, grou=0.900, answ=1.000  (741s elapsed, ETA 121s)

2026-05-15 13:41:44.015 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```json\n{\n  "context_relevance": 0.8,\n  "groundedness": 0.2,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 0.2, 'answer_relevance': 1.0}

  [llama3.1:8b] 44/50: cont=0.800, grou=0.200, answ=1.000  (755s elapsed, ETA 103s)

2026-05-15 13:42:01.936 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n    "context_relevance": 1.0,\n    "groundedness": 0.8,\n    "answer_relevance": 0.8\n}' | scores={'context_relevance': 1.0, 'groundedness': 0.8, 'answer_relevance': 0.8}

  [llama3.1:8b] 45/50: cont=1.000, grou=0.800, answ=0.800  (773s elapsed, ETA 86s)

2026-05-15 13:42:19.920 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n  "context_relevance": 0.7,\n  "groundedness": 0.8,\n  "answer_relevance": 1.0\n}' | scores={'context_relevance': 0.7, 'groundedness': 0.8, 'answer_relevance': 1.0}

  [llama3.1:8b] 46/50: cont=0.700, grou=0.800, answ=1.000  (791s elapsed, ETA 69s)

2026-05-15 13:42:33.711 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n"context_relevance": 0.7,\n"groundedness": 0.3,\n"answer_relevance": 1.0\n}' | scores={'context_relevance': 0.7, 'groundedness': 0.3, 'answer_relevance': 1.0}

  [llama3.1:8b] 47/50: cont=0.700, grou=0.300, answ=1.000  (804s elapsed, ETA 51s)

2026-05-15 13:42:50.372 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n    "context_relevance": 1.0,\n    "groundedness": 1.0,\n    "answer_relevance": 1.0\n}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 48/50: cont=1.000, grou=1.000, answ=1.000  (821s elapsed, ETA 34s)

2026-05-15 13:43:10.530 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='```\n{\n  "context_relevance": 0.8,\n  "groundedness": 1.0,\n  "answer_relevance": 1.0\n}\n```' | scores={'context_relevance': 0.8, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [llama3.1:8b] 49/50: cont=0.800, grou=1.000, answ=1.000  (841s elapsed, ETA 17s)

2026-05-15 13:43:25.389 | DEBUG    | src.judging.judge:score_all_metrics:64 - llama3.1:8b | combined | raw='{\n"answer_relevance": 0.5,\n"context_relevance": 1.0,\n"groundedness": 0.5\n}' | scores={'context_relevance': 1.0, 'groundedness': 0.5, 'answer_relevance': 0.5}

  [llama3.1:8b] 50/50: cont=1.000, grou=0.500, answ=0.500  (856s elapsed, ETA 0s)
  Saved 150 records to /workspaces/llm_judge_benchmark/data/eval/scores_llama3_1_8b.json  (856.1s total)
  Restarting Ollama...   Page cache dropped.

2026-05-15 13:43:35.692 | INFO     | src.judging.judge:warm_up:85 - qwen2.5:7b | warming up (model load may take up to 120s)...

ready.

2026-05-15 13:43:52.320 | INFO     | src.judging.judge:warm_up:99 - qwen2.5:7b | warm-up complete, model is ready

Scoring with qwen2.5:7b (50 instances × 3 metrics)...

2026-05-15 13:44:34.151 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 1/50: cont=1.000, grou=1.000, answ=1.000  (42s elapsed, ETA 2050s)

2026-05-15 13:44:52.739 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.5,"groundedness":0.8,"answer_relevance":0.9}' | scores={'context_relevance': 0.5, 'groundedness': 0.8, 'answer_relevance': 0.9}

  [qwen2.5:7b] 2/50: cont=0.500, grou=0.800, answ=0.900  (60s elapsed, ETA 1450s)

2026-05-15 13:45:07.534 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{\n  "context_relevance": 0.6,\n  "groundedness": 0.8,\n  "answer_relevance": 1.0\n}' | scores={'context_relevance': 0.6, 'groundedness': 0.8, 'answer_relevance': 1.0}

  [qwen2.5:7b] 3/50: cont=0.600, grou=0.800, answ=1.000  (75s elapsed, ETA 1178s)

2026-05-15 13:45:21.892 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.9,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 0.9, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 4/50: cont=0.900, grou=1.000, answ=1.000  (90s elapsed, ETA 1030s)

2026-05-15 13:45:39.119 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 5/50: cont=1.000, grou=1.000, answ=1.000  (107s elapsed, ETA 961s)

2026-05-15 13:45:59.457 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":0.9,"answer_relevance":1.0}' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [qwen2.5:7b] 6/50: cont=0.800, grou=0.900, answ=1.000  (127s elapsed, ETA 932s)

2026-05-15 13:46:12.677 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.5,"groundedness":0.8,"answer_relevance":0.9}' | scores={'context_relevance': 0.5, 'groundedness': 0.8, 'answer_relevance': 0.9}

  [qwen2.5:7b] 7/50: cont=0.500, grou=0.800, answ=0.900  (140s elapsed, ETA 862s)

2026-05-15 13:46:27.946 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 8/50: cont=1.000, grou=1.000, answ=1.000  (156s elapsed, ETA 817s)

2026-05-15 13:46:41.370 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 0.8, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 9/50: cont=0.800, grou=1.000, answ=1.000  (169s elapsed, ETA 770s)

2026-05-15 13:46:58.275 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 10/50: cont=1.000, grou=1.000, answ=1.000  (186s elapsed, ETA 744s)

2026-05-15 13:47:15.053 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 11/50: cont=1.000, grou=1.000, answ=1.000  (203s elapsed, ETA 719s)

2026-05-15 13:47:29.733 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":1.0,"answer_relevance":0.9}' | scores={'context_relevance': 0.8, 'groundedness': 1.0, 'answer_relevance': 0.9}

  [qwen2.5:7b] 12/50: cont=0.800, grou=1.000, answ=0.900  (217s elapsed, ETA 688s)

2026-05-15 13:47:44.882 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.7,"groundedness":0.8,"answer_relevance":0.9}' | scores={'context_relevance': 0.7, 'groundedness': 0.8, 'answer_relevance': 0.9}

  [qwen2.5:7b] 13/50: cont=0.700, grou=0.800, answ=0.900  (233s elapsed, ETA 662s)

2026-05-15 13:47:55.902 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.1,"groundedness":0.8,"answer_relevance":1.0}' | scores={'context_relevance': 0.1, 'groundedness': 0.8, 'answer_relevance': 1.0}

  [qwen2.5:7b] 14/50: cont=0.100, grou=0.800, answ=1.000  (244s elapsed, ETA 626s)

2026-05-15 13:48:12.275 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":0.9,"answer_relevance":1.0}' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [qwen2.5:7b] 15/50: cont=0.800, grou=0.900, answ=1.000  (260s elapsed, ETA 607s)

2026-05-15 13:48:27.912 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":0.9,"answer_relevance":1.0}' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 1.0}

  [qwen2.5:7b] 16/50: cont=0.800, grou=0.900, answ=1.000  (276s elapsed, ETA 586s)

2026-05-15 13:48:40.213 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.3,"groundedness":0.1,"answer_relevance":0.8}' | scores={'context_relevance': 0.3, 'groundedness': 0.1, 'answer_relevance': 0.8}

  [qwen2.5:7b] 17/50: cont=0.300, grou=0.100, answ=0.800  (288s elapsed, ETA 559s)

2026-05-15 13:48:55.714 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 18/50: cont=1.000, grou=1.000, answ=1.000  (303s elapsed, ETA 539s)

2026-05-15 13:49:12.733 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":0.9,"answer_relevance":0.9}' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 0.9}

  [qwen2.5:7b] 19/50: cont=0.800, grou=0.900, answ=0.900  (320s elapsed, ETA 523s)

2026-05-15 13:49:26.501 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.0,"groundedness":0.0,"answer_relevance":1.0}' | scores={'context_relevance': 0.0, 'groundedness': 0.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 20/50: cont=0.000, grou=0.000, answ=1.000  (334s elapsed, ETA 501s)

2026-05-15 13:49:40.034 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 21/50: cont=1.000, grou=1.000, answ=1.000  (348s elapsed, ETA 480s)

2026-05-15 13:49:47.922 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.9,"groundedness":0.8,"answer_relevance":0.7}' | scores={'context_relevance': 0.9, 'groundedness': 0.8, 'answer_relevance': 0.7}

  [qwen2.5:7b] 22/50: cont=0.900, grou=0.800, answ=0.700  (356s elapsed, ETA 453s)

2026-05-15 13:49:56.065 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":0.3,"answer_relevance":0.7}' | scores={'context_relevance': 0.8, 'groundedness': 0.3, 'answer_relevance': 0.7}

  [qwen2.5:7b] 23/50: cont=0.800, grou=0.300, answ=0.700  (364s elapsed, ETA 427s)

2026-05-15 13:50:10.831 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 0.8, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 24/50: cont=0.800, grou=1.000, answ=1.000  (379s elapsed, ETA 410s)

2026-05-15 13:50:17.583 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.5,"groundedness":0.3,"answer_relevance":0.6}' | scores={'context_relevance': 0.5, 'groundedness': 0.3, 'answer_relevance': 0.6}

  [qwen2.5:7b] 25/50: cont=0.500, grou=0.300, answ=0.600  (385s elapsed, ETA 385s)

2026-05-15 13:50:25.062 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.0,"groundedness":0.0,"answer_relevance":0.0}' | scores={'context_relevance': 0.0, 'groundedness': 0.0, 'answer_relevance': 0.0}

  [qwen2.5:7b] 26/50: cont=0.000, grou=0.000, answ=0.000  (393s elapsed, ETA 363s)

2026-05-15 13:50:39.008 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.3,"groundedness":0.8,"answer_relevance":0.9}' | scores={'context_relevance': 0.3, 'groundedness': 0.8, 'answer_relevance': 0.9}

  [qwen2.5:7b] 27/50: cont=0.300, grou=0.800, answ=0.900  (407s elapsed, ETA 346s)

2026-05-15 13:50:46.202 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.3,"groundedness":0.5,"answer_relevance":0.7}' | scores={'context_relevance': 0.3, 'groundedness': 0.5, 'answer_relevance': 0.7}

  [qwen2.5:7b] 28/50: cont=0.300, grou=0.500, answ=0.700  (414s elapsed, ETA 325s)

2026-05-15 13:50:54.207 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.3,"groundedness":0.6,"answer_relevance":0.7}' | scores={'context_relevance': 0.3, 'groundedness': 0.6, 'answer_relevance': 0.7}

  [qwen2.5:7b] 29/50: cont=0.300, grou=0.600, answ=0.700  (422s elapsed, ETA 306s)

2026-05-15 13:51:08.289 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 30/50: cont=1.000, grou=1.000, answ=1.000  (436s elapsed, ETA 291s)

2026-05-15 13:51:23.971 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 31/50: cont=1.000, grou=1.000, answ=1.000  (452s elapsed, ETA 277s)

2026-05-15 13:51:42.371 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.5,"groundedness":0.8,"answer_relevance":0.9}' | scores={'context_relevance': 0.5, 'groundedness': 0.8, 'answer_relevance': 0.9}

  [qwen2.5:7b] 32/50: cont=0.500, grou=0.800, answ=0.900  (470s elapsed, ETA 264s)

2026-05-15 13:51:54.934 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.1,"groundedness":0.1,"answer_relevance":0.1}' | scores={'context_relevance': 0.1, 'groundedness': 0.1, 'answer_relevance': 0.1}

  [qwen2.5:7b] 33/50: cont=0.100, grou=0.100, answ=0.100  (483s elapsed, ETA 249s)

2026-05-15 13:52:09.278 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.9,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 0.9, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 34/50: cont=0.900, grou=1.000, answ=1.000  (497s elapsed, ETA 234s)

2026-05-15 13:52:26.732 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 35/50: cont=1.000, grou=1.000, answ=1.000  (514s elapsed, ETA 220s)

2026-05-15 13:52:47.103 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":0.9,"answer_relevance":0.9}' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 0.9}

  [qwen2.5:7b] 36/50: cont=0.800, grou=0.900, answ=0.900  (535s elapsed, ETA 208s)

2026-05-15 13:53:00.447 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.5,"groundedness":0.6,"answer_relevance":0.7}' | scores={'context_relevance': 0.5, 'groundedness': 0.6, 'answer_relevance': 0.7}

  [qwen2.5:7b] 37/50: cont=0.500, grou=0.600, answ=0.700  (548s elapsed, ETA 193s)

2026-05-15 13:53:15.825 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 38/50: cont=1.000, grou=1.000, answ=1.000  (564s elapsed, ETA 178s)

2026-05-15 13:53:29.290 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 39/50: cont=1.000, grou=1.000, answ=1.000  (577s elapsed, ETA 163s)

2026-05-15 13:53:46.151 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.9,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 0.9, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 40/50: cont=0.900, grou=1.000, answ=1.000  (594s elapsed, ETA 148s)

2026-05-15 13:54:03.214 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 41/50: cont=1.000, grou=1.000, answ=1.000  (611s elapsed, ETA 134s)

2026-05-15 13:54:17.908 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":1.0,"answer_relevance":0.9}' | scores={'context_relevance': 0.8, 'groundedness': 1.0, 'answer_relevance': 0.9}

  [qwen2.5:7b] 42/50: cont=0.800, grou=1.000, answ=0.900  (626s elapsed, ETA 119s)

2026-05-15 13:54:33.140 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.6,"groundedness":0.7,"answer_relevance":0.8}' | scores={'context_relevance': 0.6, 'groundedness': 0.7, 'answer_relevance': 0.8}

  [qwen2.5:7b] 43/50: cont=0.600, grou=0.700, answ=0.800  (641s elapsed, ETA 104s)

2026-05-15 13:54:43.935 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.2,"groundedness":0.1,"answer_relevance":0.3}' | scores={'context_relevance': 0.2, 'groundedness': 0.1, 'answer_relevance': 0.3}

  [qwen2.5:7b] 44/50: cont=0.200, grou=0.100, answ=0.300  (652s elapsed, ETA 89s)

2026-05-15 13:55:00.858 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 45/50: cont=1.000, grou=1.000, answ=1.000  (669s elapsed, ETA 74s)

2026-05-15 13:55:16.361 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.8,"groundedness":0.9,"answer_relevance":0.9}' | scores={'context_relevance': 0.8, 'groundedness': 0.9, 'answer_relevance': 0.9}

  [qwen2.5:7b] 46/50: cont=0.800, grou=0.900, answ=0.900  (684s elapsed, ETA 59s)

2026-05-15 13:55:28.440 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.3,"groundedness":0.1,"answer_relevance":0.6}' | scores={'context_relevance': 0.3, 'groundedness': 0.1, 'answer_relevance': 0.6}

  [qwen2.5:7b] 47/50: cont=0.300, grou=0.100, answ=0.600  (696s elapsed, ETA 44s)

2026-05-15 13:55:43.711 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":1.0,"groundedness":1.0,"answer_relevance":1.0}' | scores={'context_relevance': 1.0, 'groundedness': 1.0, 'answer_relevance': 1.0}

  [qwen2.5:7b] 48/50: cont=1.000, grou=1.000, answ=1.000  (711s elapsed, ETA 30s)

2026-05-15 13:56:00.745 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.7,"groundedness":0.9,"answer_relevance":0.9}' | scores={'context_relevance': 0.7, 'groundedness': 0.9, 'answer_relevance': 0.9}

  [qwen2.5:7b] 49/50: cont=0.700, grou=0.900, answ=0.900  (728s elapsed, ETA 15s)

2026-05-15 13:56:14.438 | DEBUG    | src.judging.judge:score_all_metrics:64 - qwen2.5:7b | combined | raw='{"context_relevance":0.0,"groundedness":0.0,"answer_relevance":0.0}' | scores={'context_relevance': 0.0, 'groundedness': 0.0, 'answer_relevance': 0.0}

  [qwen2.5:7b] 50/50: cont=0.000, grou=0.000, answ=0.000  (742s elapsed, ETA 0s)
  Saved 150 records to /workspaces/llm_judge_benchmark/data/eval/scores_qwen2_5_7b.json  (742.1s total)

=== Timing summary ===
  gemma3:4b: 9.6 min
  llama3.1:8b: 14.3 min
  qwen2.5:7b: 12.4 min

## 4. Score summary

In [7]:
from IPython.display import display

score_files = list(eval_dir.glob("scores_*.json"))
if not score_files:
    print("No score files found. Run the scoring cell above first.")
else:
    all_records = []
    for f in sorted(score_files):
        all_records.extend(json.loads(f.read_text()))

    if not all_records:
        print("Score files found but all are empty — run the scoring cell above.")
    else:
        scores_df = pd.DataFrame(all_records)
        print(f"Total score records: {len(scores_df)}")
        print(f"Models scored: {sorted(scores_df['model'].unique())}")
        print("\nMean score per (model, metric):")
        display(scores_df.groupby(["model", "metric"])["score"].mean().unstack().round(3))

        summary = scores_df.groupby(["model", "metric"])["score"].agg(["mean", "std", "count"]).round(4)
        summary_path = RESULTS_DIR / "02_score_summary.json"
        summary.reset_index().to_json(summary_path, orient="records", indent=2)
        print(f"Saved score summary to {summary_path}")

Total score records: 900
Models scored: ['gemma3:1b', 'gemma3:4b', 'llama3.1:8b', 'llama3.2:1b', 'qwen2.5:1.5b', 'qwen2.5:7b']

Mean score per (model, metric):

metric        answer_relevance  context_relevance  groundedness
model
gemma3:1b                0.866              0.771         0.880
gemma3:4b                0.872              0.878         0.824
llama3.1:8b              0.810              0.868         0.786
llama3.2:1b              0.645              0.468         0.595
qwen2.5:1.5b             0.881              0.824         0.833
qwen2.5:7b               0.852              0.688         0.762

Saved score summary to /workspaces/llm_judge_benchmark/outputs/results/02_score_summary.json

## 5. Load and inspect human scores

In [8]:
human_path = ROOT / "data" / "human" / "human_scores.csv"
if human_path.exists():
    human_df = pd.read_csv(human_path)
    print(f"Human scores: {len(human_df)} instances")
    print("\nMean human scores by metric:")
    print(human_df[["context_relevance", "groundedness", "answer_relevance"]].mean().round(3).to_string())
else:
    print("Human scores not found — run notebook 01 first.")

Human scores: 50 instances

Mean human scores by metric:
context_relevance    0.741
groundedness         0.773
answer_relevance     0.819

---
**Next:** Run `03_inter_judge_agreement.ipynb` to compute kappa and correlation metrics across all annotators.